# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

target 'Will-It-Recycle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Will-It-Recycle
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'FirebaseUI'
pod 'FirebaseUI/Email'
pod 'FirebaseUI/Google'
pod 'MaterialComponents/Buttons'
pod 'MaterialComponents/Buttons+Theming'
pod 'MaterialComponents/Slider'
pod 'MaterialComponents/Cards'

end
